version: '3'

services:

  redis:
    image: redis
    container_name: redis

  client:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: work
    environment:
      - USERNAME=${USERNAME:-undefined}
      - TOKEN=${TOKEN:-undefined}
    volumes:
      - ../:/home/worker/work
      - ~/.gitconfig:/home/worker/.gitconfig:ro
      - ~/.ssh:/home/worker/.ssh:ro
    depends_on:
      - redis

