version: '3'

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379

  client:
    build:
      context: .
    container_name: work
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
    volumes:
      - ../:/home/worker/work
      - ~/.gitconfig:/home/worker/.gitconfig:ro
      - ~/.ssh:/home/worker/.ssh:ro
    depends_on:
      - redis

