version: '3'

services:

  redis:
    image: redis
    container_name: redis

  sandbox:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: sandbox
    hostname: sandbox
    environment:
      - URL=${URL:-https://sram.surf.nl}
      - USERNAME=${USERNAME:-undefined}
      - TOKEN=${TOKEN:-undefined}
      - ENTITLED=${ENTITLED:-*}
    volumes:
      - ../../:/home/worker/work
      - ~/.gitconfig:/home/worker/.gitconfig:ro
      - ~/.ssh:/home/worker/.ssh:ro
    depends_on:
      - redis

