@startuml
actor Researcher
Researcher -> Wallet: Delegate to Service
Wallet -> SRAM: Authenticate
queue Queue
Wallet --> Queue: Wrapped token for Service
Service --> Queue: Get message
Service -> Wallet: Impersonate using wrapped token
Wallet --> Service: Researcher secret to authenticate in Service
@enduml
