@startuml
User -> Service: Connect to Service...
Service -> SRAM: OIDC Authenticate
SRAM -> IDP: Redirect user to IDP
User -> IDP: User authenticates
IDP --> SRAM: IDP Authentication successfull (IDP Claim Attributes)
SRAM --> User: Check Consent
User -> SRAM: Consent OK
SRAM --> Service: SRAM Authentication succesfull (id token, access token)
Service -> SRAM: OIDC Introspect (access token)
SRAM --> Service: User Info
Service --> User: Go Ahead !
@enduml
