@startuml
group SRAM Authentiacation
    User -> Service: Connect to Service
    Service -> SRAM: OIDC Authenticate
    SRAM -> IDP: Redirect user to IDP
    User -> IDP: User authenticates
    IDP --> SRAM: IDP Authentication successfull (IDP Claim Attributes)
    SRAM --> User: Check Consent
    User -> SRAM: Consent OK
    SRAM --> Portal: SRAM Authentication succesfull (id token, access token)
    Portal -> SRAM: OIDC Introspect (access token)
    SRAM --> Service: User Info
    Service --> User: Go Ahead !
end
@enduml