@startuml
!include <osa/desktop/desktop.puml>
title SRAM to iRODS synchronization
control cronjob
participant script
database LDAP
database iCAT
participant "<$desktop>"
cronjob -> script
script <-- LDAP: Get Users & Groups
script <-- iCAT: Get Users & Groups
script -> iCAT: Sync Users & Groups
script -> "<$desktop>": Add/Remove Users
@enduml